name: CI

env:
#   MIN_SUPPORTED_RUST_VERSION: "1.46.0"
#   CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  # for multiarch gcc compatibility
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  CARGO_NDK_VERSION: "3.1.2"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  ANDROID_NDK_PACKAGE: "28.0.13004108"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  # ensure_cargo_fmt:
  #   name: Ensure 'cargo fmt' has been run
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       default: true
  #       profile: minimal
  #       components: rustfmt
  #   - uses: actions/checkout@v3
  #   - run: cargo fmt -- --check

  # min_version:
  #   name: Minimum supported rust version
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: Checkout source code
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: recursive

  #   - name: Install rust toolchain (v${{ env.MIN_SUPPORTED_RUST_VERSION }})
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}
  #       default: true
  #       profile: minimal # minimal component installation (ie, no documentation)
  #       components: clippy
  #   - name: Run clippy (on minimum supported rust version to prevent warnings we can't fix)
  #     uses: actions-rs/cargo@v1
  #     with:
  #       command: clippy
  #       args: --locked --all-targets --all-features -- --allow clippy::unknown_clippy_lints
  #   - name: Run tests
  #     uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #       args: --locked

  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: aarch64-unknown-linux-gnu   , os: ubuntu-20.04, use-cross: true }
          # - { target: arm-unknown-linux-gnueabihf , os: ubuntu-20.04, use-cross: true }
          # - { target: arm-unknown-linux-musleabihf, os: ubuntu-20.04, use-cross: true }
          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          # - { target: i686-unknown-linux-gnu      , os: ubuntu-20.04, use-cross: true }
          # - { target: i686-unknown-linux-musl     , os: ubuntu-20.04, use-cross: true }
          # - { target: x86_64-apple-darwin         , os: macos-10.15                   }
          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          # - { target: x86_64-pc-windows-msvc      , os: windows-2022                  }
          - { target: x86_64-unknown-linux-gnu    , os: ubuntu-24.04                  }
          # - { target: x86_64-unknown-linux-musl   , os: ubuntu-20.04, use-cross: true }
    steps:
    - name: Free Disk Space (Ubuntu)
      if: runner.os == 'Linux'
      # jlumbroso/free-disk-space@main is used in .github\workflows\flutter-build.yml
      # But pinning to a specific version to avoid unexpected issues is preferred.
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false

    - name: Checkout source code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Cache vcpkg artifacts
      uses: actions/cache@v4
      with:
        path: |
          /opt/artifacts/vcpkg/downloads
          /opt/artifacts/vcpkg/installed
        key: vcpkg-ci-${{ runner.os }}-${{ matrix.job.target }}-${{ env.VCPKG_COMMIT_ID }}-${{ hashFiles('vcpkg.json', 'res/vcpkg/**') }}
        restore-keys: |
          vcpkg-ci-${{ runner.os }}-${{ matrix.job.target }}-${{ env.VCPKG_COMMIT_ID }}-
          vcpkg-ci-${{ runner.os }}-${{ matrix.job.target }}-

    - name: Install prerequisites
      shell: bash
      run: |
        case ${{ matrix.job.target }} in
          x86_64-unknown-linux-gnu)
            sudo apt-get -y update
            sudo apt-get install -y \
               clang \
               cmake \
               curl \
               gcc \
               git \
               g++ \
               libpam0g-dev \
               libasound2-dev \
               libunwind-dev \
               libgstreamer1.0-dev \
               libgstreamer-plugins-base1.0-dev \
               libgtk-3-dev \
               libpulse-dev \
               libva-dev \
               libvdpau-dev \
               libxcb-randr0-dev \
               libxcb-shape0-dev \
               libxcb-xfixes0-dev \
               libxdo-dev \
               libxfixes-dev \
               nasm \
               wget
            ;;
          # arm-unknown-linux-*) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
          # aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
        esac

    - name: Setup vcpkg with Github Actions binary cache
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: /opt/artifacts/vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
        doNotCache: true

    - name: Install vcpkg dependencies
      run: |
        $VCPKG_ROOT/vcpkg install --x-install-root="$VCPKG_ROOT/installed"
      shell: bash

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.job.target }}
        components: ''

    - name: Show version information (Rust, cargo, GCC)
      shell: bash
      run: |
        gcc --version || true
        rustup -V
        rustup toolchain list
        rustup default
        cargo -V
        rustc -V

    - uses: Swatinem/rust-cache@v2

    - name: Build
      shell: bash
      run: |
        cargo build --locked --target=${{ matrix.job.target }}

    - name: clean
      shell: bash
      run: |
        cargo clean

  build-android-mobile:
    name: android-mobile
    runs-on: ubuntu-22.04
    needs: [generate-bridge]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Restore bridge files
      uses: actions/download-artifact@master
      with:
        name: bridge-artifact
        path: ./

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android NDK
      shell: bash
      run: |
        set +o pipefail
        yes | sdkmanager --licenses >/dev/null
        set -o pipefail
        sdkmanager "ndk;${{ env.ANDROID_NDK_PACKAGE }}"

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        flutter-version: ${{ env.ANDROID_FLUTTER_VERSION }}
        cache: true

    - name: Patch flutter
      shell: bash
      run: |
        patch_file="${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff"
        cd "$(dirname "$(dirname "$(which flutter)")")"
        if [[ "3.24.5" == ${{env.ANDROID_FLUTTER_VERSION}} ]]; then
          if git apply --check "$patch_file"; then
            git apply "$patch_file"
          elif git apply --reverse --check "$patch_file"; then
            echo "Flutter patch already applied"
          else
            echo "Unable to apply Flutter patch cleanly"
            exit 1
          fi
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        targets: aarch64-linux-android
        components: "rustfmt"

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: android-ubuntu-22.04

    - name: Install cargo-ndk
      shell: bash
      run: cargo install cargo-ndk --version ${{ env.CARGO_NDK_VERSION }} --locked

    - name: Cache vcpkg artifacts
      uses: actions/cache@v4
      with:
        path: |
          /opt/artifacts/vcpkg/downloads
          /opt/artifacts/vcpkg/installed
        key: vcpkg-ci-android-arm64-${{ env.VCPKG_COMMIT_ID }}-${{ hashFiles('vcpkg.json', 'res/vcpkg/**') }}
        restore-keys: |
          vcpkg-ci-android-arm64-${{ env.VCPKG_COMMIT_ID }}-
          vcpkg-ci-android-arm64-

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: /opt/artifacts/vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
        doNotCache: true

    - name: Build Android mobile
      shell: bash
      env:
        VCPKG_ROOT: /opt/artifacts/vcpkg
        ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_PACKAGE }}
      run: |
        set -euxo pipefail
        pushd flutter
        flutter pub get
        bash ./build_android_deps.sh arm64-v8a
        cargo ndk --platform 21 --target aarch64-linux-android build --release --features flutter,hwcodec
        mkdir -p android/app/src/main/jniLibs/arm64-v8a
        cp ../target/aarch64-linux-android/release/librustdesk.so android/app/src/main/jniLibs/arm64-v8a/
        cp "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so" android/app/src/main/jniLibs/arm64-v8a/
        "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip" android/app/src/main/jniLibs/arm64-v8a/*
        flutter build apk --target-platform android-arm64 --release
        popd

  build-ios-mobile:
    name: ios-mobile
    runs-on: macos-14
    needs: [generate-bridge]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Restore bridge files
      uses: actions/download-artifact@master
      with:
        name: bridge-artifact
        path: ./

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Patch flutter
      shell: bash
      run: |
        patch_file="${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff"
        cd "$(dirname "$(dirname "$(which flutter)")")"
        if [[ "3.24.5" == ${{env.FLUTTER_VERSION}} ]]; then
          if git apply --check "$patch_file"; then
            git apply "$patch_file"
          elif git apply --reverse --check "$patch_file"; then
            echo "Flutter patch already applied"
          else
            echo "Unable to apply Flutter patch cleanly"
            exit 1
          fi
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.MAC_RUST_VERSION }}
        targets: aarch64-apple-ios
        components: "rustfmt"

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ios-macos-14

    - name: Build iOS mobile
      shell: bash
      run: |
        set -euxo pipefail
        bash ./ios_arm64.sh
        pushd flutter
        flutter pub get
        flutter build ios --release --no-codesign
        popd

    # - name: Strip debug information from executable
    #   id: strip
    #   shell: bash
    #   run: |
    #     # Figure out suffix of binary
    #     EXE_suffix=""
    #     case ${{ matrix.job.target }} in
    #       *-pc-windows-*) EXE_suffix=".exe" ;;
    #     esac;

    #     # Figure out what strip tool to use if any
    #     STRIP="strip"
    #     case ${{ matrix.job.target }} in
    #       arm-unknown-linux-*) STRIP="arm-linux-gnueabihf-strip" ;;
    #       aarch64-unknown-linux-gnu) STRIP="aarch64-linux-gnu-strip" ;;
    #       *-pc-windows-msvc) STRIP="" ;;
    #     esac;

    #     # Setup paths
    #     BIN_DIR="${{ env.CICD_INTERMEDIATES_DIR }}/stripped-release-bin/"
    #     mkdir -p "${BIN_DIR}"
    #     BIN_NAME="${{ env.PROJECT_NAME }}${EXE_suffix}"
    #     BIN_PATH="${BIN_DIR}/${BIN_NAME}"

    #     # Copy the release build binary to the result location
    #     cp "target/${{ matrix.job.target }}/release/${BIN_NAME}" "${BIN_DIR}"

    #     # Also strip if possible
    #     if [ -n "${STRIP}" ]; then
    #       "${STRIP}" "${BIN_PATH}"
    #     fi

    #     # Let subsequent steps know where to find the (stripped) bin
    #     echo ::set-output name=BIN_PATH::${BIN_PATH}
    #     echo ::set-output name=BIN_NAME::${BIN_NAME}

    - name: Set testing options
      id: test-options
      shell: bash
      run: |
        # test only library unit tests and binary for arm-type targets
        unset CARGO_TEST_OPTIONS

        case ${{ matrix.job.target }} in
          arm-* | aarch64-*)
            CARGO_TEST_OPTIONS="--lib --bin ${PROJECT_NAME}"
            ;;
          *)
            CARGO_TEST_OPTIONS="--workspace --no-fail-fast -- --skip test_get_cursor_pos --skip test_get_key_state"
            ;;
        esac;

        #deprecated echo ::set-output name=CARGO_TEST_OPTIONS::${CARGO_TEST_OPTIONS}
        echo "CARGO_TEST_OPTIONS=${CARGO_TEST_OPTIONS}" >> $GITHUB_ENV
        echo "CARGO_TEST_OPTIONS=${CARGO_TEST_OPTIONS}" >> $GITHUB_OUTPUT

    - name: Run tests
      shell: bash
      run: |
        cargo test --locked --target=${{ matrix.job.target }} ${{ steps.test-options.outputs.CARGO_TEST_OPTIONS }}
